# -*- coding: utf-8 -*-
"""Heatwave_Index.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rA_mVtsjNuuSkFpmpcGhIrrnRSEdQIuR
"""

import ee
import geemap
import xarray as xr

!pip install xee
import xee

ee.Authenticate()
ee.Initialize(project ='ee-lavibas23', opt_url = 'https://earthengine-highvolume.googleapis.com')

roi = ee.Geometry.BBox(80.0, 6.5, 81.5, 8.5)

roi

collection = ee.ImageCollection("ECMWF/ERA5/DAILY").select('maximum_2m_air_temperature').filterDate('2000','2020').map(
    lambda img: img.subtract(273.15).copyProperties(img, img.propertyNames())
)

ds = xr.open_dataset(
    collection,
    engine = 'ee',
    crs = 'EPSG:4326',
    scale = 0.1,
    geometry = roi
)

ds

ds.maximum_2m_air_temperature.attrs['units'] = 'degC'

ds

!pip install xclim
import xclim

help(xclim.indices.heat_wave_index)

index = xclim.indices.heat_wave_index(
    ds.maximum_2m_air_temperature,
    thresh = '31.0 degC',
    window = 5,
    freq='YS'
)

index

index.plot(x='lon', y='lat', col='time', col_wrap=5, robust=True)

index5 = index.resample(time = '5Y').max('time').rename('Heat Wave')

index5.plot(x='lon', y='lat', col='time', col_wrap=3, robust=True)

sub = index.sel(lon=80.5, lat=7.2, method='nearest')


sub

df = sub.to_dataframe()['maximum_2m_air_temperature']

import pandas as pd

df.to_csv('heat_wave.csv')

df

df.plot()